# Introduction to Machine Learning - Task 2

Group name: Cbbayes

Team members: mcolomer (mcolomer@student.ethz.ch), pratsink (pratsink@student.ethz.ch) and scastro (scastro@student.ethz.ch)

Spring 2021

## Import libraries

In [1]:
import pandas as pd
import numpy as np

## Read data

In [2]:
# Indicate the path to the data file
path = "../data/"


train_features = pd.read_csv(path+"train_features.csv")
train_labels = pd.read_csv(path+"train_labels.csv")
test_features = pd.read_csv(path+"test_features.csv")

## Description of the train features:

All medical measurements are not available at each timestep, meaning the data contains a lot of missing values, indicated with ‘nan’ in our case. To simplify the problem, the data is already re-sampled hourly. This means that we aggregate measurements by one-hour period, thus there are only 12 rows for a given patient in the corresponding .csv file.

Either vital signs such as the Heart rate, or lab tests such as Calcium level in the patient blood. Finally, you are provided with the Age of the patient which is the same during the entire stay.

In [3]:
# Looking at the data
train_features

,pid,Time,Age,EtCO2,PTT,BUN,Lactate,Temp,Hgb,HCO3,...,Alkalinephos,SpO2,Bilirubin_direct,Chloride,Hct,Heartrate,Bilirubin_total,TroponinI,ABPs,pH
0,1,3,34.0,NaN,NaN,12.0,NaN,36.0,8.7,24.0,...,NaN,100.0,NaN,114.0,24.6,94.0,NaN,NaN,142.0,7.33
1,1,4,34.0,NaN,NaN,NaN,NaN,36.0,NaN,NaN,...,NaN,100.0,NaN,NaN,NaN,99.0,NaN,NaN,125.0,7.33
2,1,5,34.0,NaN,NaN,NaN,NaN,36.0,NaN,NaN,...,NaN,100.0,NaN,NaN,NaN,92.0,NaN,NaN,110.0,7.37
3,1,6,34.0,NaN,NaN,NaN,NaN,37.0,NaN,NaN,...,NaN,100.0,NaN,NaN,NaN,88.0,NaN,NaN,104.0,7.37
4,1,7,34.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,100.0,NaN,NaN,22.4,81.0,NaN,NaN,100.0,7.41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
227935,9999,8,85.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,80.0,NaN,NaN,110.0,NaN
227936,9999,9,85.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,83.0,NaN,NaN,123.0,NaN
227937,9999,10,85.0,NaN,NaN,NaN,NaN,36.0,NaN,NaN,...,NaN,98.0,NaN,NaN,NaN,80.0,NaN,NaN,138.0,NaN
227938,9999,11,85.0,NaN,NaN,NaN,NaN,NaN,10.2,NaN,...,NaN,98.0,NaN,NaN,31.0,75.0,NaN,NaN,125.0,NaN
227939,9999,12,85.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,79.0,NaN,NaN,128.0,NaN

In [ ]:
## Feature engineering
feature_labels = list(train_features.columns)
feature_labels = ['EtCO2', 'PTT', 'BUN','Lactate',
 'Temp', 'Hgb', 'HCO3', 'BaseExcess','RRate','Fibrinogen', 'Phosphate',
'WBC', 'Creatinine', 'PaCO2', 'AST','FiO2','Platelets','SaO2',
 'Glucose', 'ABPm', 'Magnesium',
 'Potassium', 'ABPd','Calcium', 'Alkalinephos',
 'SpO2', 'Bilirubin_direct', 'Chloride', 'Hct',
 'Heartrate', 'Bilirubin_total', 'TroponinI', 'ABPs','pH']

def create_lag(dataset, feature):
    column_lag = feature+"_lag"
    dataset[column_lag] = dataset.groupby(['pid'])[feature].diff()
    return dataset

X_train = train_features.copy()
X_test = test_features.copy()


for feature in feature_labels:
    print(feature)
    X_train[feature].fillna(X_train.groupby("pid")[feature].transform('mean'))
    X_test[feature].fillna(X_test.groupby("pid")[feature].transform('mean'))
    X_train = create_lag(X_train, feature)
    X_test = create_lag(X_test, feature)

EtCO2
PTT
BUN
Lactate
Temp

In [8]:
X_train = train_features.copy()
X_test = test_features.copy()
feature_labels = list(train_features.columns)

for feature in feature_labels:
    X_train[feature].fillna(X_train.groupby("pid")[feature].transform('mean'))
    X_test[feature].fillna(X_test.groupby("pid")[feature].transform('mean'))

X_train = X_train.fillna(X_train.mean())
X_test = X_test.fillna(X_test.mean())

X_train = X_train.groupby(by=["pid"]).mean()
X_test = X_test.groupby(by=["pid"]).mean()

In [12]:
X_train = X_train.groupby(by=["pid"]).mean()
X_test = X_test.groupby(by=["pid"]).mean()

,Time,Age,EtCO2,PTT,BUN,Lactate,Temp,Hgb,HCO3,BaseExcess,...,Alkalinephos,SpO2,Bilirubin_direct,Chloride,Hct,Heartrate,Bilirubin_total,TroponinI,ABPs,pH
pid,,,,,,,,,,,,,,,,,,,,,
0,6.5,39.0,32.560432,40.170059,22.615389,2.743194,36.497990,10.487802,21.995023,-2.024484,...,101.576297,99.417116,1.460460,105.268088,30.885954,84.508412,5.408925,7.410737,126.476344,7.369360
3,6.5,84.0,32.560432,39.934071,23.438467,2.743194,36.235798,10.655362,23.494028,-1.129381,...,99.091557,97.334232,1.460460,106.321705,31.373145,92.179284,1.670710,7.410737,117.589517,7.369232
5,6.5,62.0,32.560432,39.934071,23.438467,2.743194,36.878081,10.655362,23.494028,-1.129381,...,99.091557,96.055705,1.460460,106.321705,31.373145,66.877103,1.670710,7.410737,109.363172,7.369232
7,6.5,71.0,32.560432,48.892220,22.912183,2.743194,36.475616,9.632295,23.787187,-0.857818,...,102.735334,99.472372,1.425384,104.907946,27.880168,97.127103,1.761366,7.410737,128.598253,7.371027
9,6.5,51.0,32.560432,39.556232,27.365389,2.743194,36.794748,10.596135,23.245023,-1.129381,...,99.091557,95.972372,1.460460,105.768088,31.760954,92.960436,1.670710,7.410737,126.613172,7.369232
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31647,6.5,29.0,32.560432,39.934071,23.438467,2.743194,36.890273,10.655362,23.494028,-1.129381,...,99.091557,97.305705,1.460460,106.321705,31.373145,72.210436,1.670710,7.410737,108.098253,7.369232
31649,6.5,83.0,32.560432,39.006232,23.318594,2.599062,36.723607,11.099855,23.536192,-1.597036,...,96.167260,97.722372,1.460460,106.294897,32.679859,89.877103,1.564818,7.410737,118.848253,7.345258
31651,6.5,74.0,32.560432,39.306232,25.948722,2.743194,36.402465,10.621135,24.828356,0.319631,...,99.091557,99.805705,1.460460,105.018088,31.119288,85.627103,1.670710,7.410737,120.550942,7.370258
31652,6.5,40.0,32.560432,39.934071,21.365389,2.743194,36.878081,10.721135,23.494028,-1.129381,...,99.091557,98.305705,1.460460,106.321705,31.727621,127.627103,1.670710,6.794009,128.946506,7.369232
31655,6.5,23.0,32.560432,41.339565,23.438467,2.743194,36.926849,10.750749,23.494028,-1.129381,...,99.091557,99.805705,1.460460,106.321705,31.850383,113.127103,1.670710,7.298114,119.196506,7.369232

## Description of the train labels:

### SubTask 1) Produce (probabilistic) real-valued predictions in the interval [0, 1].
The corresponding columns containing the binary ground truth in train_labels.csv are: LABEL_BaseExcess, LABEL_Fibrinogen, LABEL_AST, LABEL_Alkalinephos, LABEL_Bilirubin_total, LABEL_Lactate, LABEL_TroponinI, LABEL_SaO2, LABEL_Bilirubin_direct, LABEL_EtCO2.

### SubTask 2) Binary: 0 or 1
The corresponding column containing the binary ground-truth in train_labels.csv is LABEL_Sepsis.

Note: for subtasks 1 and 2, you will need to produce predictions in the interval [0, 1]. How can you achieve this with an SVM? In the lecture, you have seen that the SVM prediction for binary classification is 
sign. In order to produce real-valued predictions in the interval [0, 1] with SVM, you can replace the 
sign function by the sigmoid function.

### SubTask 3) Regression 
The corresponding columns containing the real-valued ground truth in train_labels.csv are: LABEL_RRate, LABEL_ABPm, LABEL_SpO2, LABEL_Heartrate.



**Additional notes**: Both train_features.csv and test_features.csv contain missing values ('nan' entries). An important part of this project is how to deal with such missing data (known as '**data imputation**' in the ML literature) and **feature engineering** (what features can you extract from measurements taken in consecutive hours, etc.)

Ideas:

For SubTask 1a and 1b -> Engineer new features, perform SVM

For SubTask 1c -> Regression, take into account we need to output the values of the features at hour 13

## Dealing with NaN

Finally, we could fill the gaps. This is called data imputation and there are many strategies that could be used to fill the gaps. Three methods that may perform well include:

Persisting the last observed value forward (linear).
Use the median value for the hour of day within the chunk.
Use the median value for the hour of day across chunks.

In [4]:
# Looking at the class labels
train_labels

,pid,LABEL_BaseExcess,LABEL_Fibrinogen,LABEL_AST,LABEL_Alkalinephos,LABEL_Bilirubin_total,LABEL_Lactate,LABEL_TroponinI,LABEL_SaO2,LABEL_Bilirubin_direct,LABEL_EtCO2,LABEL_Sepsis,LABEL_RRate,LABEL_ABPm,LABEL_SpO2,LABEL_Heartrate
0,1,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,12.1,85.4,100.0,59.9
1,10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,17.8,100.6,95.5,85.5
2,100,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,16.5,88.3,96.5,108.1
3,1000,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,19.4,77.2,98.3,80.9
4,10000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,12.6,76.8,97.7,95.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18990,9993,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,17.1,69.8,100.0,110.7
18991,9995,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,17.6,97.3,97.8,59.2
18992,9996,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,17.3,66.3,96.9,100.3
18993,9998,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,18.8,81.5,96.9,99.4
18994,9999,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,18.0,95.5,97.0,81.9

In [14]:
test_features

,pid,Time,Age,EtCO2,PTT,BUN,Lactate,Temp,Hgb,HCO3,...,Alkalinephos,SpO2,Bilirubin_direct,Chloride,Hct,Heartrate,Bilirubin_total,TroponinI,ABPs,pH
0,0,1,39.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0,2,39.0,NaN,44.2,17.0,NaN,36.0,10.2,13.0,...,119.0,100.0,NaN,98.0,31.0,82.0,21.8,NaN,119.0,NaN
2,0,3,39.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,100.0,NaN,NaN,NaN,78.0,NaN,NaN,125.0,7.34
3,0,4,39.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,100.0,NaN,NaN,NaN,80.0,NaN,NaN,136.0,NaN
4,0,5,39.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,100.0,NaN,NaN,NaN,83.0,NaN,NaN,135.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151963,9997,8,57.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,100.0,NaN,NaN,NaN,84.0,NaN,NaN,103.0,NaN
151964,9997,9,57.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,100.0,NaN,NaN,NaN,83.0,NaN,NaN,110.0,NaN
151965,9997,10,57.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,100.0,NaN,NaN,NaN,88.0,NaN,NaN,111.0,NaN
151966,9997,11,57.0,NaN,NaN,NaN,NaN,37.0,NaN,NaN,...,NaN,100.0,NaN,NaN,NaN,89.0,NaN,NaN,118.0,NaN
151967,9997,12,57.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,100.0,NaN,NaN,NaN,86.0,NaN,NaN,111.0,NaN

## Subtask 1a

Produce (probabilistic) real-valued predictions in the interval [0, 1].
The corresponding columns containing the binary ground truth in train_labels.csv are: LABEL_BaseExcess, LABEL_Fibrinogen, LABEL_AST, LABEL_Alkalinephos, LABEL_Bilirubin_total, LABEL_Lactate, LABEL_TroponinI, LABEL_SaO2, LABEL_Bilirubin_direct, LABEL_EtCO2.

In [24]:
from sklearn.svm import LinearSVC
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

labels_a = ["LABEL_BaseExcess", "LABEL_Fibrinogen", 
          "LABEL_AST", "LABEL_Alkalinephos", "LABEL_Bilirubin_total", 
          "LABEL_Lactate", "LABEL_TroponinI", "LABEL_SaO2", "LABEL_Bilirubin_direct", "LABEL_EtCO2"]


def fit_SVM(X_train, y_train, X_test):
    clf = make_pipeline(StandardScaler(), LinearSVC())
    clf.fit(X_train, y_train)
    predicted = clf.predict(X_test)
    return predicted


output_dataframe = test_features.groupby(by=["pid"]).mean()
for feature in labels_a:
    print(feature)
    y_train = train_labels[feature]
    output_dataframe[feature] = fit_SVM(X_train, y_train, X_test)

LABEL_BaseExcess

/opt/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)

AttributeError: 'Pipeline' object has no attribute 'coef_'

In [42]:
from sklearn.svm import LinearSVC
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn import linear_model


labels_a = ["LABEL_BaseExcess", "LABEL_Fibrinogen", 
          "LABEL_AST", "LABEL_Alkalinephos", "LABEL_Bilirubin_total", 
          "LABEL_Lactate", "LABEL_TroponinI", "LABEL_SaO2", "LABEL_Bilirubin_direct", "LABEL_EtCO2"]


def fit_RFC(X_train, y_train, X_test):
    clf = RandomForestClassifier()
    clf.fit(X_train, y_train)
    predicted = clf.predict(X_test)
    return predicted


def fit_Lasso(X_train, y_train, X_test):
    clf = linear_model.Lasso(alpha=0.1)
    clf.fit(X_train, y_train)
    predicted = clf.predict(X_test)
    return predicted


output_dataframe = test_features.groupby(by=["pid"], as_index=False).mean()
for feature in labels_a:
    print(feature)
    y_train = train_labels[feature]
    output_dataframe[feature] = fit_RFC(X_train, y_train, X_test)
    
labels_b = ["LABEL_Sepsis"]

for feature in labels_b:
    print(feature)
    y_train = train_labels[feature]
    output_dataframe[feature] = fit_RFC(X_train, y_train, X_test)
    
labels_c = ["LABEL_RRate", "LABEL_ABPm", "LABEL_SpO2", "LABEL_Heartrate"]


for feature in labels_c:
    print(feature)
    y_train = train_labels[feature]
    output_dataframe[feature] = fit_Lasso(X_train, y_train, X_test)

LABEL_BaseExcess

/opt/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

LABEL_Fibrinogen

/opt/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

LABEL_AST

/opt/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

LABEL_Alkalinephos

/opt/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

LABEL_Bilirubin_total

/opt/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

LABEL_Lactate

/opt/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

LABEL_TroponinI

/opt/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

LABEL_SaO2

/opt/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

LABEL_Bilirubin_direct

/opt/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

LABEL_EtCO2

/opt/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

LABEL_Sepsis

/opt/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

LABEL_RRate
LABEL_ABPm
LABEL_SpO2
LABEL_Heartrate

In [33]:
output_columns = ["pid"]+labels_a+labels_b+labels_c
output_columns = list(sample.columns)
output = output_dataframe[output_columns]
output.to_csv("../output/"+'prediction_2.zip', index=False, float_format='%.3f', compression='zip')